/**
 * PostgREST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Angebot { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Note: This is a Foreign Key to `artikel.id`.<fk table=\'artikel\' column=\'id\'/>
     */
    artikel_id?: number;
    bietender_id: string;
    betrag: number;
    erstellt_am?: string;
}

