/**
 * PostgREST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArtikelAngebote { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    id?: number;
    titel?: string;
    beschreibung?: string;
    anbieter_id?: string;
    preis_vorschlag?: number;
    status?: string;
    angelegt_am?: string;
    angebote?: object;
}

