 name: DockerSuuq

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: suuqplattform
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  postgrest:
    image: postgrest/postgrest:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/suuqplattform
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMA: suuq
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_MODE: ignore-privileges
      PGRST_LOG_LEVEL: debug